<!doctype html><html lang="en" style="overscroll-behavior-x:none"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta property="og:author" content="https://ivesvh.com"><meta property="og:site_name" content="CodeSandbox"><link href="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>
<style>
svg {
background: transparent;
}
path {
fill: black;
}
@media (prefers-color-scheme: dark)  {
path {
fill: white;
}
}
</style>
<path fill-rule='evenodd' clip-rule='evenodd' d='M81.8182 18.1818V81.8182H18.1818V18.1818H81.8182ZM10 90V10H90V90H10Z'/>
</svg>" rel="icon"/><link rel="mask-icon" href="/csb-ios.svg" color="#000"><link rel="manifest" href="/manifest.json"><script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script><script>WebFont.load({google:{families:["Source Code Pro:500","Roboto:300,400,500,700","Poppins:300,400,500,600,700"]}})</script><!-- Injected by server: --><link rel="alternate" type="application/json+oembed" href="https://codesandbox.io/oembed?url=https://codesandbox.io/s/musing-mendeleev-ns9664&format=json" title="musing-mendeleev-ns9664" /><title>musing-mendeleev-ns9664 - CodeSandbox</title><link href="/static/fonts/monolisa.css" rel="stylesheet"><link crossorigin="anonymous" rel="preload" href="/static/fonts/inter/Inter-Regular.woff2" as="font"><link crossorigin="anonymous" rel="preload" href="/static/fonts/inter/Inter-Medium.woff2" as="font"><link crossorigin="anonymous" rel="preload" href="/static/fonts/inter/Inter-Bold.woff2" as="font"><link href="/static/fonts/inter/inter.css" rel="stylesheet"><link crossorigin="anonymous" rel="preload" href="/static/fonts/everett/TWKEverett-Light-web.woff2" as="font"><link crossorigin="anonymous" rel="preload" href="/static/fonts/everett/TWKEverett-Regular-web.woff2" as="font"><link crossorigin="anonymous" rel="preload" href="/static/fonts/everett/TWKEverett-Medium-web.woff2" as="font"><link href="/static/fonts/everett/everett.css" rel="stylesheet"><!-- Google Tag Manager --><script>!function(e,t,a,n){e[n]=e[n]||[],e[n].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});var g=t.getElementsByTagName(a)[0],m=t.createElement(a);m.async=!0,m.src="https://www.googletagmanager.com/gtm.js?id=GTM-T3L6RFK",g.parentNode.insertBefore(m,g)}(window,document,"script","dataLayer")</script><!-- End Google Tag Manager --><!-- <script async src="//cdn.headwayapp.co/widget.js"></script> --><script src="https://codesandbox.io/static/browserfs12/browserfs.min.js" type="text/javascript"></script><script>BrowserFS&&(window.process={env:{VSCODE_DEV:!1},nextTick:function(e){return requestAnimationFrame(e)},once:BrowserFS.BFSRequire("process").once,removeListener:function(){}},window.Buffer=BrowserFS.BFSRequire("buffer").Buffer)</script><link data-name="/public/vscode33/vs/editor/editor.main" rel="preload" as="style" href="/public/vscode33/vs/editor/codesandbox.editor.main.css"><link rel="preload" as="script" href="/public/vscode33/vs/editor/codesandbox.editor.main.js"><link href="https://codesandbox.io/static/css/common.0cbbfe89.chunk.css" rel="stylesheet"><link href="https://codesandbox.io/static/css/vendors~app.ba9a586c.chunk.css" rel="stylesheet"><link href="https://codesandbox.io/static/css/default~app~embed.1f247b7e.chunk.css" rel="stylesheet"><link href="https://codesandbox.io/static/css/app.10caa73c.css" rel="stylesheet"><meta property="og:title" name="og:title" content="musing-mendeleev-ns9664 - CodeSandbox">
<meta property="twitter:title" name="twitter:title" content="musing-mendeleev-ns9664 - CodeSandbox">
<meta property="description" name="description" content="musing-mendeleev-ns9664 using loader-utils, react, react-dom, react-scripts">
<meta property="og:description" name="og:description" content="musing-mendeleev-ns9664 using loader-utils, react, react-dom, react-scripts">
<meta property="twitter:description" name="twitter:description" content="musing-mendeleev-ns9664 using loader-utils, react, react-dom, react-scripts">
<meta property="article:published_time" name="article:published_time" content="2023-05-12T10:07:30">
<meta property="article:modified_time" name="article:modified_time" content="2023-05-12T10:30:04">
<meta property="article:section" name="article:section" content="create-react-app">
<meta property="og:type" name="og:type" content="article">
<meta property="og:url" name="og:url" content="https://codesandbox.io/s/ns9664">
<meta property="twitter:site" name="twitter:site" content="@codesandbox">
<script type="application/ld+json">{"name":"musing-mendeleev-ns9664","text":null,"keywords":"create-react-app","author":null,"image":{"url":"https://codesandbox.io/api/v1/sandboxes/ns9664/screenshot.png","@type":"ImageObject"},"url":"https://codesandbox.io/s/ns9664","publisher":{"name":"CodeSandbox","logo":{"width":1200,"url":"https://codesandbox.io/static/img/banner.png","height":630,"@type":"ImageObject"},"@type":"Organization"},"codeRepository":"https://codesandbox.io/s/ns9664","codeSampleType":"full solution","dateCreated":"2023-05-12T10:07:30","dateModified":"2023-05-12T10:30:04","isBasedOn":null,"programmingLanguage":"create-react-app","thumbnailUrl":"https://codesandbox.io/api/v1/sandboxes/ns9664/screenshot.png","workExample":{"url":"https://ns9664.csb.app","applicationCategory":"create-react-app","operatingSystem":"Web app","screenshot":"https://codesandbox.io/api/v1/sandboxes/ns9664/screenshot.png","@type":"SoftwareApplication"},"@context":"https://schema.org","@type":"SoftwareSourceCode"}</script>
<meta property="robots" name="robots" content="noindex">
<meta property="og:image" name="og:image" content="https://codesandbox.io/api/v1/sandboxes/ns9664/screenshot.png">
<meta property="twitter:image:src" name="twitter:image:src" content="https://codesandbox.io/api/v1/sandboxes/ns9664/screenshot.png">
<meta property="og:image:alt" name="og:image:alt" content="A preview of musing-mendeleev-ns9664">
<meta property="og:image:width" name="og:image:width" content="1200">
<meta property="twitter:image:width" name="twitter:image:width" content="1200">
<meta property="og:image:height" name="og:image:height" content="630">
<meta property="twitter:image:height" name="twitter:image:height" content="630">
<meta property="twitter:card" name="twitter:card" content="summary_large_image">
</head><body style="margin:0;padding:0"><!-- Google Tag Manager (noscript) --><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T3L6RFK" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><!-- End Google Tag Manager (noscript) --><div id="root"></div><script src="https://codesandbox.io/static/js/vendors~app~codemirror-editor~monaco-editor~sandbox.ad4e6d3c4.chunk.js" crossorigin="anonymous"></script><script src="https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js" crossorigin="anonymous"></script><script src="https://codesandbox.io/static/js/common-sandbox.d3049e87f.chunk.js" crossorigin="anonymous"></script><script src="https://codesandbox.io/static/js/vendors~app~codemirror-editor~monaco-editor.bf93486bf.chunk.js"></script><script src="https://codesandbox.io/static/js/0.2455d7681.chunk.js"></script><script src="https://codesandbox.io/static/js/vendors~app~embed~sandbox-startup.6c550ef8a.chunk.js" crossorigin="anonymous"></script><script src="https://codesandbox.io/static/js/common.9637ade4f.chunk.js"></script><script src="https://codesandbox.io/static/js/vendors~app~sandbox.aca52037e.chunk.js" crossorigin="anonymous"></script><script src="https://codesandbox.io/static/js/vendors~app~monaco-editor.44b1703f7.chunk.js"></script><script src="https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js"></script><script src="https://codesandbox.io/static/js/default~app~embed~sandbox~sandbox-startup.b2134d8a8.chunk.js" crossorigin="anonymous"></script><script src="https://codesandbox.io/static/js/default~app~embed~sandbox.151677cc0.chunk.js" crossorigin="anonymous"></script><script src="https://codesandbox.io/static/js/default~app~embed.c643de405.chunk.js"></script><script src="https://codesandbox.io/static/js/default~app~monaco-editor.d45c42400.chunk.js"></script><script src="https://codesandbox.io/static/js/app.645a9bdc4.js"></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v2cb3a2ab87c5498db5ce7e6608cf55231689030342039" integrity="sha512-DI3rPuZDcpH/mSGyN22erN5QFnhl760f50/te7FTIYxodEF8jJnSFnfnmG/c+osmIQemvUrnBtxnMpNdzvx1/g==" data-cf-beacon='{"rayId":"7e696fd5fab53c13","token":"7449176f14aa420c959831edd48bd5b7","version":"2023.4.0","si":100}' crossorigin="anonymous"></script>
</body></html>